### PR TITLE
Integrate SynchrotronTerm in distribution

### PR DESCRIPTION
**Pull request by hoppe93**
Synchrotron losses can now be included in all 3D Fokker-Planck equations.

### CODE REVIEW

**Comment by hoppe93** [comment]
Should we implement a synchrotron test first? If so, how should it be designed?

**Comment by Embreus** [comment]
> Should we implement a synchrotron test first? If so, how should it be designed?

A possibility would be to set up a simulation resulting in a bump on tail distribution, and compare the location of the maximum with a CODE simulation.

**Review by Embreus — CHANGES_REQUESTED** [review]
Looks ready to go as soon as the test runs!

**Comment by hoppe93** [comment]
No, this was just a merge with master to get the new xi grids. I still have to make the synchrotron tests run before we merge into master...

**Comment by Embreus** [comment]
> No, this was just a merge with master to get the new xi grids. I still have to make the synchrotron tests run before we merge into master...

Oh, never mind then! Misinterpreted my notification.

**Pull request merged**
